
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class salarios extends javax.swing.JFrame {

    /**
     * Creates new form salarios
     */
    public salarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        primero = new javax.swing.JTextField();
        segundo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ape1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ape2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nacimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sala = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        extras = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("primer nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel2.setText("segundo nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 14, -1, -1));

        primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeroActionPerformed(evt);
            }
        });
        getContentPane().add(primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 91, -1));
        getContentPane().add(segundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 11, 99, -1));

        jLabel3.setText("primer apellido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, -1));
        getContentPane().add(ape1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 95, -1));

        jLabel4.setText("segundo apellido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 52, -1, -1));
        getContentPane().add(ape2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 49, 99, -1));

        jLabel5.setText("año de nacimiento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        getContentPane().add(nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 87, 149, -1));

        jLabel6.setText("salario");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 90, -1, -1));
        getContentPane().add(sala, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 87, 99, -1));

        jLabel7.setText("horas extras");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 121, -1, -1));
        getContentPane().add(extras, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 118, 99, -1));

        jButton1.setText("insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 172, -1, -1));

        jButton2.setText("eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 172, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre completo", "Edad", "Salario", "Horas Extras", "Salario Final"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 206, 503, 105));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void primeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primeroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo= (DefaultTableModel) tabla.getModel();
        int anio,edad;
        float extra,extra2,sal,s,h,salex;
        String nombrecompleto="",n,nn,a,aa;
        
        n=primero.getText();
        nn=segundo.getText();
        a=ape1.getText();
        aa=ape2.getText();
    nombrecompleto=nombrecompleto+n+" "+nn+" "+a+" "+aa;
        
   edad=Integer.parseInt(nacimiento.getText());
   anio=2019-edad;
   s=Float.parseFloat(sala.getText());
   h=Float.parseFloat(extras.getText());
   extra=(float)(s*0.01);
   extra2=s*h;
   salex=s+extra2;
        
       
        Object  [] fila=new Object [5];
        fila [0]= nombrecompleto;
        fila [1]= String.valueOf(anio);
        fila [2]= sala.getText();
        fila [3]=  String.valueOf(extra);
         fila [4]=String.valueOf(salex);
        
  modelo.addRow(fila);
 tabla.setModel(modelo); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         DefaultTableModel modelo= (DefaultTableModel) tabla.getModel();
        int a=tabla.getSelectedRow();
        if (a<0){
            JOptionPane.showConfirmDialog(null,"debe seleccionar una fila");
        }else{
            int confirmar=JOptionPane.showConfirmDialog(null,"esta seguro??");
            if (JOptionPane.OK_OPTION==confirmar){
                modelo.removeRow(a);
                JOptionPane.showMessageDialog(null,"Row eliminado");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ape1;
    private javax.swing.JTextField ape2;
    private javax.swing.JTextField extras;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nacimiento;
    private javax.swing.JTextField primero;
    private javax.swing.JTextField sala;
    private javax.swing.JTextField segundo;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
