
 
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class quitar_vocal extends javax.swing.JFrame {

    /**
     * Creates new form quitar_vocal
     */
    public quitar_vocal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vocales = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        parra = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        a = new javax.swing.JRadioButton();
        e = new javax.swing.JRadioButton();
        i = new javax.swing.JRadioButton();
        o = new javax.swing.JRadioButton();
        u = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ingrese parrafo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 14, -1, -1));

        parra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parraActionPerformed(evt);
            }
        });
        getContentPane().add(parra, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 11, 161, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("VOCALES"));

        vocales.add(a);
        a.setText("a");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        vocales.add(e);
        e.setText("e");

        vocales.add(i);
        i.setText("i");

        vocales.add(o);
        o.setText("o");

        vocales.add(u);
        u.setText("u");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(a)
                .addGap(18, 18, 18)
                .addComponent(o)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(e)
                    .addComponent(i))
                .addGap(14, 14, 14)
                .addComponent(u)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a)
                    .addComponent(o))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e)
                    .addComponent(u))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(i)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 60, 120, -1));

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "parrafo sin vocal", "longitud"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 201, 320, 101));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parraActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
DefaultTableModel modelo= (DefaultTableModel) tabla.getModel();
String palabra,l="",aa="",ee="",ii="",oo="",uu="";
   int x,y;
   char ch;
   palabra=parra.getText();
   y=palabra.length();
   
   if(a.isSelected()){
       for(x=0;x<y;x=x+1){
           ch=palabra.charAt(x);
           if (ch!='a'){
               aa=aa+ch;
           } 
       }
       l=l+y;
       Object  [] fila=new Object [2];
       fila [0]= aa;
        fila [1]= l;
       
 
   modelo.addRow(fila);
tabla.setModel(modelo);
    
 
    }   
   if(e.isSelected()){
    for(x=0;x<y;x=x+1){
           ch=palabra.charAt(x);
           if (ch!='e'){
               ee=ee+ch;
        }    
          } 
    l=l+y;
       Object  [] fila=new Object [2];
       fila [0]= aa;
        fila [1]= l;
       
 
   modelo.addRow(fila);
tabla.setModel(modelo);
    
 
    }
    if(i.isSelected()){
       for(x=0;x<y;x=x+1){
           ch=palabra.charAt(x);
           if (ch!='i'){
               ii=ii+ch;
           } 
       }
       l=l+y;
       Object  [] fila=new Object [2];
       fila [0]= aa;
        fila [1]= l;
       
 
   modelo.addRow(fila);
tabla.setModel(modelo);
   }
    
     if(o.isSelected()){
       for(x=0;x<y;x=x+1){
           ch=palabra.charAt(x);
           if (ch!='o'){
               oo=oo+ch;
           } 
       }
       l=l+y;
       Object  [] fila=new Object [2];
       fila [0]= aa;
        fila [1]= l;
       
 
   modelo.addRow(fila);
tabla.setModel(modelo);
        
     }   
      if(u.isSelected()){
       for(x=0;x<y;x=x+1){
           ch=palabra.charAt(x);
           if (ch!='u'){
               uu=uu+ch;
           } 
       }
       l=l+y;
       Object  [] fila=new Object [2];
       fila [0]= aa;
        fila [1]= l;
       
 
   modelo.addRow(fila);
tabla.setModel(modelo);
        
     }   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quitar_vocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quitar_vocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quitar_vocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quitar_vocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quitar_vocal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a;
    private javax.swing.JRadioButton e;
    private javax.swing.JRadioButton i;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton o;
    private javax.swing.JTextField parra;
    private javax.swing.JTable tabla;
    private javax.swing.JRadioButton u;
    private javax.swing.ButtonGroup vocales;
    // End of variables declaration//GEN-END:variables
}
