 
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




public class vocales_numeros extends javax.swing.JFrame {

    /**
     * Creates new form vocales_numeros
     */
    public vocales_numeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caracter = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        texto = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        voc = new javax.swing.JRadioButton();
        num = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ingrese parrafo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("CARACTER"));

        caracter.add(voc);
        voc.setText("vocales");

        caracter.add(num);
        num.setText("numeros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voc)
                    .addComponent(num))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(voc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(num)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "caracter", "aparece"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    DefaultTableModel model=(DefaultTableModel)tabla.getModel();
String t;
int i,x,alt=0,elt=0,ilt=0,olt=0,ult=0,n1=0,n2=0,n3=0,n4=0,n5=0,n6=0,n7=0,n8=0,n9=0,n0=0;
char ch;
t=texto.getText();
x=t.length();

 if(voc.isSelected()){ 
for (i=0;i<x;i=i+1){
ch=t.charAt(i);
 if(ch=='a'){
  alt=alt+1;
  }
  if(ch=='e'){
  elt=elt+1;
  }
  if(ch=='i'){
  ilt=ilt+1;
  }
  if(ch=='o'){
  olt=olt+1;
  }
  if(ch=='u'){
  ult=ult+1;
  }
}
Object[] file=new Object[2];
file[0]="a";
file[1]=String.valueOf(alt);   
model.addRow(file);
file[0]="e";
file[1]=String.valueOf(elt);   
model.addRow(file);
file[0]="i";
file[1]=String.valueOf(ilt); 
model.addRow(file);
file[0]="o";
file[1]=String.valueOf(olt);   
model.addRow(file);
file[0]="u";
file[1]=String.valueOf(ult);   
model.addRow(file);
tabla.setModel(model);

}

if(num.isSelected()){ 
for (i=0;i<x;i=i+1){
ch=t.charAt(i);
if(ch=='1'){
  n1=n1+1;
  }
  if(ch=='2'){
  n2=n2+1;
  }
   if(ch=='3'){
  n3=n3+1;
  }
    if(ch=='4'){
  n4=n4+1;
  }
     if(ch=='5'){
  n5=n5+1;
  }
       if(ch=='6'){
  n6=n6+1;
  }
       if(ch=='7'){
  n7=n7+1;
  }
       if(ch=='8'){
  n8=n8+1;
  }
    if(ch=='9'){
  n9=n9+1;
  }
      if(ch=='0'){
  n0=n0+1;
  }  
}Object[] file=new Object[2];
file[0]="1";
file[1]=String.valueOf(n1);
model.addRow(file);
file[0]="2";
file[1]=String.valueOf(n2);
model.addRow(file);
file[0]="3";
file[1]=String.valueOf(n3);
model.addRow(file);
file[0]="4";
file[1]=String.valueOf(n4);
model.addRow(file);
file[0]="5";
file[1]=String.valueOf(n5);
model.addRow(file);
file[0]="6";
file[1]=String.valueOf(n6);
model.addRow(file);
file[0]="7";
file[1]=String.valueOf(n7);
model.addRow(file);
file[0]="8";
file[1]=String.valueOf(n8);
model.addRow(file);
file[0]="9";
file[1]=String.valueOf(n9);
model.addRow(file);
file[0]="0";
file[1]=String.valueOf(n0);
model.addRow(file);
tabla.setModel(model);
}

     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vocales_numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vocales_numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vocales_numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vocales_numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vocales_numeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup caracter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton num;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField texto;
    private javax.swing.JRadioButton voc;
    // End of variables declaration//GEN-END:variables
}
