import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ProjectSumaValores extends javax.swing.JFrame {

    /**
     * Creates new form ProjectSumaValores
     */
    public ProjectSumaValores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parra = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        num1 = new javax.swing.JTextField();
        num2 = new javax.swing.JTextField();
        num3 = new javax.swing.JTextField();
        num4 = new javax.swing.JTextField();
        num5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        resul = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parra.setText("ingrese valores");
        getContentPane().add(parra, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 27, -1, -1));

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jButton2.setText("eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        getContentPane().add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 59, 52, -1));
        getContentPane().add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 57, -1));
        getContentPane().add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 59, -1));
        getContentPane().add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 63, -1));
        getContentPane().add(num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 69, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "A", "B", "C", "D", "E", "Total"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 149, -1, 92));

        jButton3.setText("calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));
        getContentPane().add(resul, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // BOTON ELIMINAR
        DefaultTableModel modelo= (DefaultTableModel) tabla.getModel();
        int a=tabla.getSelectedRow();
        if (a<0){
            JOptionPane.showConfirmDialog(null,"debe seleccionar una fila");
        }else{
            int confirmar=JOptionPane.showConfirmDialog(null,"esta seguro??");
            if (JOptionPane.OK_OPTION==confirmar){
                modelo.removeRow(a);
                JOptionPane.showMessageDialog(null,"Row eliminado");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//BOTON INSERTAR
        
       String nume1,nume2,nume3,nume4,nume5;
       int total,n1,n2,n3,n4,n5;
        
     DefaultTableModel modelo= (DefaultTableModel) tabla.getModel();

      tabla.getModel();
      nume1=num1.getText();
      nume2=num2.getText();
      nume3=num3.getText();
      nume4=num4.getText();
      nume5=num5.getText();
      
      n1=Integer.parseInt(nume1);
      n2=Integer.parseInt(nume2);
      n3=Integer.parseInt(nume3);
      n4=Integer.parseInt(nume5);
      n5=Integer.parseInt(nume1);
      
      total=n1+n2+n3+n4+n5;
      
      
      Object  [] fila=new Object [6];
       fila [0]= n1;
       fila [1]= n2;
       fila [2]= n3;
       fila [3]= n4;
       fila [4]=n5;
       fila [5]=String.valueOf(total);
       
        modelo.addRow(fila);
        tabla.setModel(modelo); 
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // BOTON CALCULAR
        String t=" ";
        int total=0,otrasuma=0;
        int f;
        DefaultTableModel modelo= (DefaultTableModel) tabla.getModel();
        tabla.getModel();
        for(f=0;f<modelo.getRowCount();f++){
            t=(String)modelo.getValueAt(f,5);
            total=Integer.parseInt(t);
            otrasuma=otrasuma+total;
            
        }
        resul.setText(String.valueOf(otrasuma));
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectSumaValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectSumaValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectSumaValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectSumaValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectSumaValores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.JTextField num3;
    private javax.swing.JTextField num4;
    private javax.swing.JTextField num5;
    private javax.swing.JLabel parra;
    private javax.swing.JTextField resul;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
