/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class DianaVictores extends javax.swing.JFrame {

    /**
     * Creates new form DianaVictores
     */
    public DianaVictores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        parra = new javax.swing.JTextField();
        primero = new javax.swing.JTextField();
        ultim = new javax.swing.JTextField();
        espa = new javax.swing.JTextField();
        conso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ingrese parrafo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText("primeros caracteres");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jButton1.setText("calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel3.setText("ultimos caracteres ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel4.setText("espacios en blanco");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        getContentPane().add(parra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 180, -1));
        getContentPane().add(primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 120, -1));
        getContentPane().add(ultim, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 120, -1));
        getContentPane().add(espa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 120, -1));
        getContentPane().add(conso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 120, -1));

        jLabel5.setText("consonate");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 80, -1));

        jLabel7.setText("valor de n");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // primeras y ultimas
    String parrafo,newpal="",ultimas=" ",primeras="";
        char ch,prl,ul=' ';
        int i,x,longi,longi2;
       
    parrafo=parra.getText();
    longi=parrafo.length();
    for (i=0;i<longi;i=i+1){
    ch=parrafo.charAt(i);
    newpal=newpal+ch;
    if (ch==' '){
        prl=newpal.charAt(0);
        longi2=newpal.length()-1;
        ul=newpal.charAt(1);
        ultimas=ultimas+ul;
        primeras=primeras+prl;
        newpal="" ;
        }//if
    
        
    }
    
         primero.setText(ultimas);
         ultim.setText(primeras);  
        
        
         
      //  ----- CONSONANTES, ESPACIOS----------- 
          String parrafos,consonante=" ";
     int e=0;
     
     parrafo=parra.getText();
     longi=parrafo.length();
     for (i=0;i<longi;i=i+1){
         ch=parrafo.charAt(i);
         
              if(ch!='a'&& ch!='e'&& ch!='i'&& ch!='o'&&ch!='u'){
                 consonante=consonante+ch;
         }
          if (ch==' '){
              e=e+1; 
     }
     }
       
        conso.setText(consonante);
        espa.setText(String.valueOf(e));
        
     //-----VALOR DE N-------

           float numero;
        float total=0;
        int a;
        
        numero=Float.parseFloat(n.getText());
        for (a=1; a<=numero; a=a+1){
            total=total+a;
        }
     
     
     
     
     
     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DianaVictores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DianaVictores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DianaVictores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DianaVictores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DianaVictores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField conso;
    private javax.swing.JTextField espa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField n;
    private javax.swing.JTextField parra;
    private javax.swing.JTextField primero;
    private javax.swing.JTextField ultim;
    // End of variables declaration//GEN-END:variables
}
