/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class proyecto6 extends javax.swing.JFrame {

    /**
     * Creates new form proyecto6
     */
    public proyecto6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p1 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        boton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        m = new javax.swing.JTextField();
        lo1 = new javax.swing.JTextField();
        lo2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("primera palabra");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setText("segunda palabra");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 60, -1));
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 60, -1));

        boton.setText("calcular");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        getContentPane().add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel3.setText("mensaje");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        getContentPane().add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 170, -1));

        lo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lo1ActionPerformed(evt);
            }
        });
        getContentPane().add(lo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 70, -1));
        getContentPane().add(lo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
      String palabra, palabra2;
      int longi1,longi2;
      palabra=p1.getText();
      palabra2=p2.getText();
      longi1=palabra.length();
      longi2=palabra2.length();
          if(longi1==longi2){
              m.setText("SON IGUALES");
       if(longi1>longi2){
           m.setText("palabra1 es mayor");
       }
      if(longi2>longi1){
          m.setText("palabra2 es mayor");
      }
             
        
        
        
      
          
      }
        
        
    }//GEN-LAST:event_botonActionPerformed

    private void lo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proyecto6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proyecto6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proyecto6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proyecto6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proyecto6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lo1;
    private javax.swing.JTextField lo2;
    private javax.swing.JTextField m;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    // End of variables declaration//GEN-END:variables
}
