import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class exam_final extends javax.swing.JFrame {

    /**
     * Creates new form exam_final
     */
    public exam_final() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        parra = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        al = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setForeground(new java.awt.Color(255, 51, 204));
        jLabel1.setText("INGRESE PARRAFO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 50, 100, -1));

        parra.setDisabledTextColor(new java.awt.Color(51, 255, 204));
        parra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parraActionPerformed(evt);
            }
        });
        getContentPane().add(parra, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 230, -1));

        tabla.setForeground(new java.awt.Color(255, 153, 51));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parte", "Longitud"
            }
        ));
        tabla.setGridColor(new java.awt.Color(204, 204, 0));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, 121));

        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        al.setText("Al reves");
        getContentPane().add(al, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        tabla2.setForeground(new java.awt.Color(153, 0, 0));
        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Al reves"
            }
        ));
        jScrollPane2.setViewportView(tabla2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 160, 120));

        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setText("calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        tabla3.setForeground(new java.awt.Color(0, 51, 51));
        tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Total vocales", "Solo cononante"
            }
        ));
        jScrollPane3.setViewportView(tabla3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 360, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // EXAMEN FINAL
        String palabra;
   int x,i=0,n=0;
   char ch,ch2;
   palabra=parra.getText();
   i=palabra.length();
   n=i;
  StringTokenizer st=new StringTokenizer (palabra);
  String pal="";
while (st.hasMoreTokens()){
pal=st.nextToken();
    DefaultTableModel modelo= (DefaultTableModel) tabla.getModel();
           Object [] fila=new Object[10];
           fila[0]=pal;
           fila[1]=pal.length();
           modelo.addRow(fila);
tabla.setModel(modelo);
    
   
      } 

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
         String palabra;
   int x,i,n;
   char ch,ch2;
   palabra=parra.getText();
   i=palabra.length();
   n=i;
 
 String alrevez="";
 for(x=0;x<i;x=x+1){
 n=n-1;
 ch2=palabra.charAt(n);
 alrevez=alrevez+ch2;
 }
if(al.isSelected()){
StringTokenizer st=new StringTokenizer (alrevez);
String alr="";
while (st.hasMoreTokens()){
alr=st.nextToken();
 DefaultTableModel modelo= (DefaultTableModel) tabla2.getModel();
           Object [] fila=new Object[2];
           fila[0]=alr;
           fila[1]=alr.length();
           modelo.addRow(fila);
tabla2.setModel(modelo);
}
} 
   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String total,vocal;
    
        
       
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exam_final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exam_final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exam_final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exam_final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exam_final().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton al;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField parra;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tabla2;
    private javax.swing.JTable tabla3;
    // End of variables declaration//GEN-END:variables
}
