

 
import javax.swing.table.DefaultTableModel;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;






public class project_piramide extends javax.swing.JFrame {

    /**
     * Creates new form project_piramide
     */
    public project_piramide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vocales = new javax.swing.ButtonGroup();
        v = new javax.swing.JPanel();
        opta = new javax.swing.JRadioButton();
        opte = new javax.swing.JRadioButton();
        opti = new javax.swing.JRadioButton();
        opto = new javax.swing.JRadioButton();
        optu = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        v.setBorder(javax.swing.BorderFactory.createTitledBorder("VOCALES"));
        v.setToolTipText("");

        vocales.add(opta);
        opta.setText("a");

        vocales.add(opte);
        opte.setText("e");
        opte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opteActionPerformed(evt);
            }
        });

        vocales.add(opti);
        opti.setText("i");
        opti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optiActionPerformed(evt);
            }
        });

        vocales.add(opto);
        opto.setText("o");

        vocales.add(optu);
        optu.setText("u");

        javax.swing.GroupLayout vLayout = new javax.swing.GroupLayout(v);
        v.setLayout(vLayout);
        vLayout.setHorizontalGroup(
            vLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vLayout.createSequentialGroup()
                .addGroup(vLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(opta))
                    .addComponent(opte))
                .addGap(18, 18, 18)
                .addComponent(opti)
                .addGap(39, 39, 39)
                .addGroup(vLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(optu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opto))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        vLayout.setVerticalGroup(
            vLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vLayout.createSequentialGroup()
                .addGroup(vLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(opti))
                    .addGroup(vLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(vLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vLayout.createSequentialGroup()
                                .addComponent(opto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(optu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(vLayout.createSequentialGroup()
                                .addComponent(opta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(opte)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(v, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

        jLabel1.setText("conteo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 67, -1, -1));
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 64, 47, -1));

        jButton1.setText("calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 142, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "letras", "cantidad"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 208, 284, 96));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opteActionPerformed

    private void optiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


   DefaultTableModel modelo= (DefaultTableModel) tabla.getModel();
        
        String letra="",c1;
        String pal="";
        int i, k, conteo, cont;
        
        if (opta.isSelected()){
            letra="a";
         }
        
         if (opte.isSelected()){
            letra="e";
         }
         
          if (opti.isSelected()){
            letra="i";
         }
        
           if (opto.isSelected()){
            letra="o";
         }
        
            if (optu.isSelected()){
            letra="u";
         }
            
    c1=c.getText();
    cont=Integer.parseInt(c1);

    for (i=1;i<=cont;i=i+1){
        for(k=1;k<=i;k=k+1){
            pal=pal+letra;
        }
       
        Object  [] fila=new Object [2];
        fila [0]= pal;
        fila [1]= i;
        modelo.addRow(fila);
        pal="";
         
tabla.setModel(modelo);
        
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**++
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project_piramide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project_piramide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project_piramide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project_piramide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project_piramide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opta;
    private javax.swing.JRadioButton opte;
    private javax.swing.JRadioButton opti;
    private javax.swing.JRadioButton opto;
    private javax.swing.JRadioButton optu;
    private javax.swing.JTable tabla;
    private javax.swing.JPanel v;
    private javax.swing.ButtonGroup vocales;
    // End of variables declaration//GEN-END:variables
}
