/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class proyectos_cambios extends javax.swing.JFrame {

    /**
     * Creates new form proyectos_cambios
     */
    public proyectos_cambios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ESPACIOO = new javax.swing.ButtonGroup();
        PARESS = new javax.swing.ButtonGroup();
        IMPARESS = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        aste = new javax.swing.JRadioButton();
        division = new javax.swing.JRadioButton();
        por = new javax.swing.JRadioButton();
        par6 = new javax.swing.JPanel();
        par2 = new javax.swing.JRadioButton();
        par4 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        par8 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        uno = new javax.swing.JRadioButton();
        tres = new javax.swing.JRadioButton();
        cinco = new javax.swing.JRadioButton();
        siete = new javax.swing.JRadioButton();
        nueve = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        resul = new javax.swing.JTextField();
        parra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ingrese parrafo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ESPACIO"));

        ESPACIOO.add(aste);
        aste.setText("*");

        ESPACIOO.add(division);
        division.setText("/");

        ESPACIOO.add(por);
        por.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aste)
                    .addComponent(division)
                    .addComponent(por))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(aste)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(division)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(por)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        par6.setBorder(javax.swing.BorderFactory.createTitledBorder("PARES"));

        PARESS.add(par2);
        par2.setText("2");

        PARESS.add(par4);
        par4.setText("4");

        PARESS.add(jRadioButton6);
        jRadioButton6.setText("6");

        PARESS.add(par8);
        par8.setText("8");

        javax.swing.GroupLayout par6Layout = new javax.swing.GroupLayout(par6);
        par6.setLayout(par6Layout);
        par6Layout.setHorizontalGroup(
            par6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(par6Layout.createSequentialGroup()
                .addGroup(par6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(par6Layout.createSequentialGroup()
                        .addComponent(par2)
                        .addGap(36, 36, 36)
                        .addComponent(jRadioButton6))
                    .addGroup(par6Layout.createSequentialGroup()
                        .addComponent(par4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(par8)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        par6Layout.setVerticalGroup(
            par6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(par6Layout.createSequentialGroup()
                .addGroup(par6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(par2)
                    .addComponent(jRadioButton6))
                .addGroup(par6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(par6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(par4))
                    .addGroup(par6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(par8)))
                .addGap(0, 51, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("IMPARES"));

        IMPARESS.add(uno);
        uno.setText("1");

        IMPARESS.add(tres);
        tres.setText("3");

        IMPARESS.add(cinco);
        cinco.setText("5");

        IMPARESS.add(siete);
        siete.setText("7");

        IMPARESS.add(nueve);
        nueve.setText("9");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(cinco)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uno)
                    .addComponent(tres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nueve)
                    .addComponent(siete))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uno)
                    .addComponent(siete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tres)
                    .addComponent(nueve))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cinco)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("convertida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(par6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(parra, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addComponent(resul, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(parra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(par6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(resul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String te,espacio="",par="",o="",newpal="";
        char ch,ch2;
        int i,longi,j=0;
        te=parra.getText();
       longi=te.length();
        //if (por.isSelected()){
            if(por.isSelected()){
                espa='%';
            }
       for (i=0;i<6;i=i+2){
           ch=par.charAt(i);
           //j=i+1;
           //ch2=par.charAt(j);
           if (ch!=' '){
               newpal=newpal+ch;      
               }
            if (ch==' '){
             newpal=newpal+espacio;
            
            }
        
            
        }
           
       //}
       
       resul.setText(newpal);
       
       
        //for (i=0;i<=longi;i=i+2){
          //  ch=parrafo.charAt(i);
            //if (ch!=' '){
             //  if(aste.isSelected()){
                //    espacio="asterisco"+"*";
                //}
                //if(division.isSelected()){
                 //   espacio="division"+"/";
                //}
                //if(por.isSelected()){
                  //  espacio="porciento"+"%";
                //}
                
                // if(par2.isSelected()){
                 //   pares=newpal+"2";
              //  }
                
               //   if(par4.isSelected()){
               //     pares=newpal+"4";
              //  }
              //    if(par6.isSelected()){
                 //   pares=newpal+"6";
              //  }
               //     if(par8.isSelected()){
                //    pares=newpal+"8";
                //}
           // }
            
       // }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proyectos_cambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proyectos_cambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proyectos_cambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proyectos_cambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proyectos_cambios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ESPACIOO;
    private javax.swing.ButtonGroup IMPARESS;
    private javax.swing.ButtonGroup PARESS;
    private javax.swing.JRadioButton aste;
    private javax.swing.JRadioButton cinco;
    private javax.swing.JRadioButton division;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton nueve;
    private javax.swing.JRadioButton par2;
    private javax.swing.JRadioButton par4;
    private javax.swing.JPanel par6;
    private javax.swing.JRadioButton par8;
    private javax.swing.JTextField parra;
    private javax.swing.JRadioButton por;
    private javax.swing.JTextField resul;
    private javax.swing.JRadioButton siete;
    private javax.swing.JRadioButton tres;
    private javax.swing.JRadioButton uno;
    // End of variables declaration//GEN-END:variables
}
