/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class project_insertar extends javax.swing.JFrame {

    /** Creates new form project_insertar */
    public project_insertar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simbo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        parra = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        di = new javax.swing.JRadioButton();
        nume = new javax.swing.JRadioButton();
        pregu = new javax.swing.JRadioButton();
        mas = new javax.swing.JRadioButton();
        por = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        conver = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ingrese parrafo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        getContentPane().add(parra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 166, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("SIMBOLOS"));

        simbo.add(di);
        di.setText("/");

        simbo.add(nume);
        nume.setText("#");

        simbo.add(pregu);
        pregu.setText("?");

        simbo.add(mas);
        mas.setText("+");

        por.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(di)
                .addGap(18, 18, 18)
                .addComponent(nume)
                .addGap(18, 18, 18)
                .addComponent(pregu)
                .addGap(18, 18, 18)
                .addComponent(mas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(por)
                .addGap(0, 121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(di)
                    .addComponent(nume)
                    .addComponent(pregu)
                    .addComponent(mas)
                    .addComponent(por))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 350, 70));

        jLabel2.setText("espacios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 50, -1));

        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 50, -1));

        jButton1.setText("calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel3.setText("convertida");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        getContentPane().add(conver, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String palabra="",newpal="",division="",hola="", que="",masa="";
    String num;
    int espacios,cont,i;
    char ch;
    int longi;
    palabra=parra.getText();
      longi=palabra.length();
    num=n.getText();
    espacios=Integer.parseInt(num);
 cont=0;
    
   if(nume.isSelected()){
    for(i=0;i<longi;i=i+1){
       ch= palabra.charAt(i);
       newpal=newpal+ch;
       cont=cont+1;
    
    if (cont==espacios){
        newpal=newpal+"#";
        cont=0;
    }
    }  
       }
    
  if (di.isSelected()){
   for(i=0;i<longi;i=i+1){
       ch= palabra.charAt(i);
       newpal=newpal+ch;
       cont=cont+1;
    
    if (cont==espacios){
        newpal=newpal+"/";
        cont=0;
    }
    }  
       }
   
  if (pregu.isSelected()){
   for(i=0;i<longi;i=i+1){
       ch= palabra.charAt(i);
       newpal=newpal+ch;
       cont=cont+1;
    
    if (cont==espacios){
        newpal=newpal+"?";
        cont=0;
    }
    }  
       }
   
   if (mas.isSelected()){
   for(i=0;i<longi;i=i+1){
       ch= palabra.charAt(i);
       newpal=newpal+ch;
       cont=cont+1;
    
    if (cont==espacios){
        newpal=newpal+"+";
        cont=0;
    }
    }  
       }
   
   if (por.isSelected()){
   for(i=0;i<longi;i=i+1){
       ch= palabra.charAt(i);
       newpal=newpal+ch;
       cont=cont+1;
    
    if (cont==espacios){
        newpal=newpal+"%";
        cont=0;
    }
    }  
       }
    
    conver.setText(newpal);
    
    
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project_insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project_insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project_insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project_insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project_insertar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField conver;
    private javax.swing.JRadioButton di;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mas;
    private javax.swing.JTextField n;
    private javax.swing.JRadioButton nume;
    private javax.swing.JTextField parra;
    private javax.swing.JRadioButton por;
    private javax.swing.JRadioButton pregu;
    private javax.swing.ButtonGroup simbo;
    // End of variables declaration//GEN-END:variables

}
