/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class Quitavocales extends javax.swing.JFrame {

    /**
     * Creates new form Quitavocales
     */
    public Quitavocales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vocales = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        parra = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        resul = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        a = new javax.swing.JRadioButton();
        e = new javax.swing.JRadioButton();
        vocali = new javax.swing.JRadioButton();
        o = new javax.swing.JRadioButton();
        u = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ing.parrafo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 38, -1, -1));
        getContentPane().add(parra, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 35, 155, -1));

        jButton1.setText("calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));
        getContentPane().add(resul, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 136, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Vocales"));

        vocales.add(a);
        a.setText("a");

        vocales.add(e);
        e.setText("e");

        vocales.add(vocali);
        vocali.setText("i");

        vocales.add(o);
        o.setText("o");

        vocales.add(u);
        u.setText("u");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(a)
                .addGap(18, 18, 18)
                .addComponent(e)
                .addGap(18, 18, 18)
                .addComponent(vocali)
                .addGap(18, 18, 18)
                .addComponent(o)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(u)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a)
                    .addComponent(e)
                    .addComponent(vocali)
                    .addComponent(o)
                    .addComponent(u))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 300, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String p,newpal=" ";
        int longi,i;
        char ch,letra='a';
       p=parra.getText();
       longi=p.length();
       if (a.isSelected()){
           
       letra='a';
       for (i=0;i<longi;i=i+1){
           ch=p.charAt(i);
           if(ch!=letra){
               newpal=newpal+ch;
           }//for
       }    
       resul.setText(newpal);
       }
    
        if (e.isSelected()){
           
        letra='e';
       for (i=0;i<longi;i=i+1){
           ch=p.charAt(i);
           if(ch!=letra){
               newpal=newpal+ch;
           }//for
       }  
       resul.setText(newpal);
       }
       
         if (vocali.isSelected()){
           
        letra='i';
       for (i=0;i<longi;i=i+1){
           ch=p.charAt(i);
           if(ch!=letra){
               newpal=newpal+ch;
           }//for
       }    
       resul.setText(newpal);
       }
         
          if (o.isSelected()){
           
        letra='o';
       for (i=0;i<longi;i=i+1){
           ch=p.charAt(i);
           if(ch!=letra){
               newpal=newpal+ch;
           }//for
       } 
       resul.setText(newpal);
       }
          
           if (u.isSelected()){
           
        letra='u';
       for (i=0;i<longi;i=i+1){
           ch=p.charAt(i);
           if(ch!=letra){
               newpal=newpal+ch;
           }//for
       }  
       resul.setText(newpal);
       }

        
        




       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quitavocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quitavocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quitavocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quitavocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quitavocales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a;
    private javax.swing.JRadioButton e;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton o;
    private javax.swing.JTextField parra;
    private javax.swing.JTextField resul;
    private javax.swing.JRadioButton u;
    private javax.swing.ButtonGroup vocales;
    private javax.swing.JRadioButton vocali;
    // End of variables declaration//GEN-END:variables
}
